# Generated by Django 3.1.7 on 2021-03-05 11:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0002_auto_20210304_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_availability',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Остаток'),
        ),
    ]
