# Generated by Django 3.1.6 on 2021-04-02 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_auto_20210305_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.IntegerField(verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productbucket', to='watches.product')),
            ],
        ),
    ]
