# Generated by Django 3.1.7 on 2021-04-26 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('watches', '0006_order_productorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorder',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProductCart',
        ),
    ]
